# Generated by Django 5.2.16 on 2026-09-26 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
        ('repartidores', '0001_initial'),
        ('solicitudes', '0004_eventosolicitud_latitud_eventosolicitud_longitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=16)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reportada_en', models.DateTimeField()),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='jornadas.jornadarepartidor')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='repartidores.repartidor')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'incidencia',
                'verbose_name_plural': 'incidencias',
                'db_table': 'incidencias',
                'ordering': ('-reportada_en', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave_almacenamiento', models.CharField(max_length=500, unique=True)),
                ('tipo_contenido', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capturada_en', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_incidencias', to='repartidores.repartidor')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'evidencia de incidencia',
                'verbose_name_plural': 'evidencias de incidencias',
                'db_table': 'evidencias_incidencia',
                'ordering': ('capturada_en', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventoIncidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('REPORTADA', 'Reportada'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada'), ('EVIDENCIA_REGISTRADA', 'Evidencia registrada')], max_length=24)),
                ('estado_anterior', models.CharField(blank=True, choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada')], max_length=16, null=True)),
                ('estado_nuevo', models.CharField(blank=True, choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada')], max_length=16, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_incidencias_realizados', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'evento de incidencia',
                'verbose_name_plural': 'eventos de incidencias',
                'db_table': 'eventos_incidencia',
                'ordering': ('creado_en', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['repartidor', '-reportada_en'], name='inc_repart_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['jornada', 'estado'], name='inc_jornada_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['solicitud', '-reportada_en'], name='inc_solic_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidencia',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ABIERTA', 'EN_REVISION', 'CERRADA'])), name='inc_estado_valido_ck'),
        ),
        migrations.AddConstraint(
            model_name='incidencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitud__isnull', True), ('longitud__isnull', True)), models.Q(('latitud__gte', -90), ('latitud__lte', 90), ('longitud__gte', -180), ('longitud__lte', 180)), _connector='OR'), name='inc_coordenadas_validas_ck'),
        ),
        migrations.AddConstraint(
            model_name='incidencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cerrada_en__isnull', True), ('estado', 'ABIERTA'), ('revisada_en__isnull', True), ('revisada_por__isnull', True)), models.Q(('cerrada_en__isnull', True), ('estado', 'EN_REVISION'), ('revisada_en__isnull', False), ('revisada_por__isnull', False)), models.Q(('cerrada_en__isnull', False), ('estado', 'CERRADA'), ('revisada_en__isnull', False), ('revisada_por__isnull', False)), _connector='OR'), name='inc_revision_consistente_ck'),
        ),
        migrations.AddIndex(
            model_name='evidenciaincidencia',
            index=models.Index(fields=['incidencia', '-capturada_en'], name='evid_inc_incid_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciaincidencia',
            index=models.Index(fields=['repartidor', '-capturada_en'], name='evid_inc_repart_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenciaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='evid_inc_latitud_valida_ck'),
        ),
        migrations.AddConstraint(
            model_name='evidenciaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='evid_inc_longitud_valida_ck'),
        ),
        migrations.AddIndex(
            model_name='eventoincidencia',
            index=models.Index(fields=['incidencia', 'creado_en'], name='evt_inc_incid_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['REPORTADA', 'EN_REVISION', 'CERRADA', 'EVIDENCIA_REGISTRADA'])), name='evt_inc_tipo_valido_ck'),
        ),
    ]
