# Generated by Django 5.2.16 on 2026-09-24 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_initial'),
        ('repartidores', '0001_initial'),
        ('solicitudes', '0002_catalogo_tipos_servicio'),
        ('ubicaciones', '0002_catalogo_tipos_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=16)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('REASIGNADA', 'Reasignada')], default='ACTIVA', max_length=16)),
                ('asignada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'asignación de solicitud',
                'verbose_name_plural': 'asignaciones de solicitudes',
                'db_table': 'asignaciones_solicitud',
                'ordering': ('-asignada_en', '-id'),
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='repartidor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignadas', to='repartidores.repartidor'),
        ),
        migrations.AlterField(
            model_name='eventosolicitud',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA', 'Asignada'), ('REASIGNADA', 'Reasignada')], max_length=80),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['repartidor_asignado', 'estado'], name='solicitud_repart_est_idx'),
        ),
        migrations.AddField(
            model_name='asignacionsolicitud',
            name='asignada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_solicitudes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionsolicitud',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_solicitudes', to='repartidores.repartidor'),
        ),
        migrations.AddField(
            model_name='asignacionsolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='solicitudes.solicitud'),
        ),
        migrations.AddIndex(
            model_name='asignacionsolicitud',
            index=models.Index(fields=['solicitud', '-asignada_en'], name='asig_sol_solic_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsolicitud',
            index=models.Index(fields=['repartidor', 'estado'], name='asig_sol_repart_est_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacionsolicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('solicitud',), name='asig_sol_activa_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asignacionsolicitud',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['MANUAL', 'AUTOMATICA'])), name='asig_sol_tipo_valido_ck'),
        ),
        migrations.AddConstraint(
            model_name='asignacionsolicitud',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVA', 'FINALIZADA', 'CANCELADA', 'REASIGNADA'])), name='asig_sol_estado_valido_ck'),
        ),
        migrations.AddConstraint(
            model_name='asignacionsolicitud',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ACTIVA'), ('finalizada_en__isnull', True)), models.Q(('estado__in', ('FINALIZADA', 'CANCELADA', 'REASIGNADA')), ('finalizada_en__isnull', False)), _connector='OR'), name='asig_sol_cierre_valido_ck'),
        ),
    ]
