# Generated by Django 5.2.16 on 2026-09-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartidores', '0001_initial'),
        ('solicitudes', '0003_asignacionsolicitud_solicitud_repartidor_asignado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosolicitud',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eventosolicitud',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eventosolicitud',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_solicitudes', to='repartidores.repartidor'),
        ),
        migrations.AlterField(
            model_name='eventosolicitud',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA', 'Asignada'), ('REASIGNADA', 'Reasignada'), ('HACIA_RECOLECCION', 'Hacia recolección'), ('LLEGADA_RECOLECCION', 'Llegada a recolección'), ('RECOLECTADA', 'Recolectada'), ('EN_TRANSITO', 'En tránsito'), ('LLEGADA_DESTINO', 'Llegada a destino'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('RECOLECCION_FALLIDA', 'Recolección fallida'), ('ENTREGA_FALLIDA', 'Entrega fallida'), ('EVIDENCIA_REGISTRADA', 'Evidencia registrada')], max_length=80),
        ),
        migrations.AddConstraint(
            model_name='eventosolicitud',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitud__isnull', True), ('longitud__isnull', True)), models.Q(('latitud__gte', -90), ('latitud__lte', 90), ('longitud__gte', -180), ('longitud__lte', 180)), _connector='OR'), name='evento_solicitud_gps_valido_ck'),
        ),
    ]
