# Generated by Django 5.2.16 on 2026-09-21 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_telefonico', models.CharField(max_length=10)),
                ('codigo_moneda', models.CharField(max_length=3)),
                ('zona_horaria_predeterminada', models.CharField(max_length=64)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'db_table': 'paises',
                'ordering': ('nombre',),
                'indexes': [models.Index(fields=['activo'], name='paises_activo_idx')],
            },
        ),
    ]
