# Generated by Django 5.2.16 on 2026-10-01 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0005_modalidades_y_movimiento_especial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SOLICITUD_ASIGNADA', 'Solicitud asignada'), ('SOLICITUD_REASIGNADA', 'Solicitud reasignada'), ('SOLICITUD_RETIRADA', 'Solicitud retirada'), ('SOLICITUD_PRIORITARIA', 'Solicitud prioritaria')], max_length=40)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField()),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='solicitudes.eventosolicitud')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='solicitudes.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones_usuario',
                'ordering': ('-creado_en', '-id'),
                'indexes': [models.Index(fields=['usuario', 'leida_en', '-creado_en'], name='notif_usuario_lectura_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'evento'), name='notif_usuario_evento_uniq')],
            },
        ),
    ]
