# Generated by Django 5.2.16 on 2026-09-24 20:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=32, unique=True)),
                ('tipo', models.CharField(choices=[('MOTOCICLETA', 'Motocicleta'), ('AUTOMOVIL', 'Automóvil'), ('PANEL', 'Panel'), ('ESPECIAL', 'Especial'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacidad_carga_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='organizaciones.empresa')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'db_table': 'vehiculos',
                'ordering': ('placa', 'id'),
                'indexes': [models.Index(fields=['empresa', 'estado'], name='vehiculo_emp_estado_idx'), models.Index(fields=['estado'], name='vehiculo_estado_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['MOTOCICLETA', 'AUTOMOVIL', 'PANEL', 'ESPECIAL', 'OTRO'])), name='vehiculo_tipo_valido_ck'), models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'MANTENIMIENTO', 'FUERA_SERVICIO', 'INACTIVO'])), name='vehiculo_estado_valido_ck'), models.CheckConstraint(condition=models.Q(('capacidad_carga_kg__isnull', True), ('capacidad_carga_kg__gt', 0), _connector='OR'), name='vehiculo_capacidad_positiva_ck')],
            },
        ),
    ]
