# Generated by Django 5.2.16 on 2026-09-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='ubicaciones.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['pais', 'estado'], name='empresas_pais_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['estado'], name='empresas_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa', 'estado'], name='sucursales_empresa_estado_idx'),
        ),
    ]
