# Generated by Django 5.2.16 on 2026-09-24 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0001_initial'),
        ('organizaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_operativo', models.CharField(choices=[('OFFLINE', 'Desconectado'), ('AVAILABLE', 'Disponible'), ('ON_ROUTE', 'En ruta'), ('PAUSED', 'Pausado'), ('OUT_OF_SERVICE', 'Fuera de servicio')], default='OFFLINE', max_length=20)),
                ('capacidad', models.CharField(choices=[('EMPTY', 'Vacío'), ('AVAILABLE_SPACE', 'Con espacio disponible'), ('FULL', 'Lleno')], default='EMPTY', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repartidores', to='organizaciones.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_repartidor', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repartidores', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'motorista',
                'verbose_name_plural': 'motoristas',
                'db_table': 'repartidores',
                'ordering': ('usuario__nombres', 'usuario__apellidos', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoRepartidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_anterior', models.CharField(choices=[('OFFLINE', 'Desconectado'), ('AVAILABLE', 'Disponible'), ('ON_ROUTE', 'En ruta'), ('PAUSED', 'Pausado'), ('OUT_OF_SERVICE', 'Fuera de servicio')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('OFFLINE', 'Desconectado'), ('AVAILABLE', 'Disponible'), ('ON_ROUTE', 'En ruta'), ('PAUSED', 'Pausado'), ('OUT_OF_SERVICE', 'Fuera de servicio')], max_length=20)),
                ('capacidad_anterior', models.CharField(choices=[('EMPTY', 'Vacío'), ('AVAILABLE_SPACE', 'Con espacio disponible'), ('FULL', 'Lleno')], max_length=20)),
                ('capacidad_nueva', models.CharField(choices=[('EMPTY', 'Vacío'), ('AVAILABLE_SPACE', 'Con espacio disponible'), ('FULL', 'Lleno')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_operativos_repartidores', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_operativo', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'cambio operativo de motorista',
                'verbose_name_plural': 'cambios operativos de motoristas',
                'db_table': 'historial_estado_repartidor',
                'ordering': ('-creado_en', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['empresa', 'activo', 'estado_operativo'], name='repart_emp_act_est_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['estado_operativo', 'capacidad'], name='repart_estado_cap_idx'),
        ),
        migrations.AddConstraint(
            model_name='repartidor',
            constraint=models.CheckConstraint(condition=models.Q(('estado_operativo__in', ['OFFLINE', 'AVAILABLE', 'ON_ROUTE', 'PAUSED', 'OUT_OF_SERVICE'])), name='repart_estado_valido_ck'),
        ),
        migrations.AddConstraint(
            model_name='repartidor',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad__in', ['EMPTY', 'AVAILABLE_SPACE', 'FULL'])), name='repart_capacidad_valida_ck'),
        ),
        migrations.AddIndex(
            model_name='historialestadorepartidor',
            index=models.Index(fields=['repartidor', '-creado_en'], name='hist_repart_fecha_idx'),
        ),
    ]
