# Generated by Django 5.2.16 on 2026-09-21 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografia', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUbicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de ubicación',
                'verbose_name_plural': 'tipos de ubicación',
                'db_table': 'tipos_ubicacion',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('GOOGLE', 'Google'), ('REGISTRADA_USUARIO', 'Registrada por usuario')], max_length=24)),
                ('identificador_lugar_google', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_administrativo_1', models.CharField(blank=True, max_length=150, null=True)),
                ('nivel_administrativo_2', models.CharField(blank=True, max_length=150, null=True)),
                ('localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('telefono', models.CharField(blank=True, max_length=32, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_atencion', models.JSONField(blank=True, null=True)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('verificada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=16)),
                ('creada_por', models.UUIDField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='geografia.pais')),
                ('tipo_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='ubicaciones.tipoubicacion')),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'db_table': 'ubicaciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UbicacionEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('permite_origen', models.BooleanField(default=False)),
                ('permite_destino', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_autorizadas', to='organizaciones.empresa')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_autorizadas', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'ubicación autorizada para empresa',
                'verbose_name_plural': 'ubicaciones autorizadas para empresas',
                'db_table': 'ubicaciones_empresa',
                'ordering': ('empresa_id', 'ubicacion_id'),
            },
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['pais', 'estado'], name='ubicaciones_pais_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['identificador_lugar_google'], name='ubicaciones_google_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='ubicaciones_latitud_rango_ck'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='ubicaciones_longitud_rango_ck'),
        ),
        migrations.AddIndex(
            model_name='ubicacionempresa',
            index=models.Index(fields=['empresa', 'estado'], name='ubic_empresa_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'ubicacion'), name='ubic_empresa_relacion_uniq'),
        ),
    ]
