# Generated by Django 5.2.16 on 2026-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_catalogo_tipos_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
