# Generated by Django 5.2.16 on 2026-09-21 19:36

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAutenticacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('hash_token_refresco', models.CharField(max_length=64, unique=True)),
                ('identificador_token', models.CharField(max_length=64, unique=True)),
                ('familia', models.UUIDField()),
                ('identificador_dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('agente_usuario', models.TextField(blank=True, null=True)),
                ('expira_en', models.DateTimeField()),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.CharField(blank=True, choices=[('ROTACION', 'Rotación del token de refresco'), ('CIERRE_SESION', 'Cierre de sesión'), ('CIERRE_TOTAL', 'Cierre de todas las sesiones'), ('REUTILIZACION_TOKEN', 'Reutilización de token'), ('USUARIO_INACTIVO', 'Usuario inactivo'), ('EXPIRACION', 'Expiración')], max_length=80, null=True)),
                ('reemplazada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_reemplazadas', to='autenticacion.sesionautenticacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_autenticacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de autenticación',
                'verbose_name_plural': 'sesiones de autenticación',
                'db_table': 'sesiones_autenticacion',
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['usuario', 'revocado_en'], name='ses_auth_usr_rev_idx'), models.Index(fields=['familia', 'revocado_en'], name='ses_auth_fam_rev_idx'), models.Index(fields=['expira_en'], name='ses_auth_expira_idx'), models.Index(fields=['identificador_dispositivo'], name='ses_auth_dispositivo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('motivo_revocacion__isnull', True), ('reemplazada_por__isnull', True), ('revocado_en__isnull', True)), models.Q(('motivo_revocacion__isnull', False), ('revocado_en__isnull', False)), _connector='OR'), name='ses_auth_revocacion_valida_ck')],
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
