# Generated by Django 5.2.16 on 2026-09-26 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUbicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.UUIDField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('velocidad_metros_segundo', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rumbo_grados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('359.99'))])),
                ('registrada_en', models.DateTimeField()),
                ('es_operativo', models.BooleanField(default=False)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ubicacion', to='jornadas.jornadarepartidor')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ubicacion', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'registro de ubicación',
                'verbose_name_plural': 'registros de ubicación',
                'db_table': 'registros_ubicacion',
                'ordering': ('-registrada_en', '-id'),
                'indexes': [models.Index(fields=['repartidor', '-registrada_en'], name='reg_ubi_repart_fecha_idx'), models.Index(fields=['jornada', '-registrada_en'], name='reg_ubi_jornada_fecha_idx'), models.Index(fields=['repartidor', 'es_operativo', '-registrada_en'], name='reg_ubi_repart_op_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('repartidor', 'id_cliente'), name='reg_ubi_repart_cliente_uniq'), models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90), ('longitud__gte', -180), ('longitud__lte', 180)), name='reg_ubi_coordenadas_validas_ck'), models.CheckConstraint(condition=models.Q(('precision_metros__isnull', True), ('precision_metros__gte', 0), _connector='OR'), name='reg_ubi_precision_valida_ck'), models.CheckConstraint(condition=models.Q(('velocidad_metros_segundo__isnull', True), ('velocidad_metros_segundo__gte', 0), _connector='OR'), name='reg_ubi_velocidad_valida_ck'), models.CheckConstraint(condition=models.Q(('rumbo_grados__isnull', True), models.Q(('rumbo_grados__gte', 0), ('rumbo_grados__lt', 360)), _connector='OR'), name='reg_ubi_rumbo_valido_ck')],
            },
        ),
    ]
