# Generated by Django 5.2.16 on 2026-09-21 17:22

import apps.usuarios.administradores
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(blank=True, db_column='hash_contrasena', max_length=128, null=True, verbose_name='contraseña')),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True, verbose_name='último acceso')),
                ('identificador_autenticacion_externa', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=16)),
                ('es_personal', models.BooleanField(default=False)),
                ('es_superusuario', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='organizaciones.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='organizaciones.sucursal')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'ordering': ('correo',),
                'indexes': [models.Index(fields=['empresa', 'estado'], name='usuarios_empresa_estado_idx'), models.Index(fields=['sucursal', 'estado'], name='usuarios_sucursal_estado_idx'), models.Index(fields=['estado'], name='usuarios_estado_idx')],
            },
            managers=[
                ('objetos', apps.usuarios.administradores.AdministradorUsuarios()),
            ],
        ),
    ]
