# Generated by Django 5.2.16 on 2026-09-21 17:34

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'permisos',
                'ordering': ('codigo',),
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'ordering': ('nombre',),
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_roles', to='usuarios.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_permisos', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'permiso de rol',
                'verbose_name_plural': 'permisos de roles',
                'db_table': 'permisos_rol',
                'ordering': ('rol_id', 'permiso_id'),
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='permiso',
            name='roles',
            field=models.ManyToManyField(related_name='permisos', through='usuarios.PermisoRol', to='usuarios.rol'),
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_alcance', models.CharField(choices=[('GLOBAL', 'Global'), ('EMPRESA', 'Empresa'), ('SUCURSAL', 'Sucursal')], max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('asignado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_roles_usuarios', to='organizaciones.empresa')),
                ('revocado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_revocados', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuarios', to='usuarios.rol')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_roles_usuarios', to='organizaciones.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rol de usuario',
                'verbose_name_plural': 'roles de usuarios',
                'db_table': 'roles_usuario',
                'ordering': ('usuario_id', 'rol_id', 'asignado_en'),
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='permisorol',
            index=models.Index(fields=['rol', 'activo'], name='permisos_rol_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='permisorol',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='permisos_rol_relacion_uniq'),
        ),
        migrations.AddIndex(
            model_name='rolusuario',
            index=models.Index(fields=['usuario', 'activo'], name='rol_usr_usuario_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='rolusuario',
            index=models.Index(fields=['empresa', 'activo'], name='rol_usr_empresa_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='rolusuario',
            index=models.Index(fields=['sucursal', 'activo'], name='rol_usr_sucursal_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolusuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', True), ('sucursal__isnull', True), ('tipo_alcance', 'GLOBAL')), models.Q(('empresa__isnull', False), ('sucursal__isnull', True), ('tipo_alcance', 'EMPRESA')), models.Q(('empresa__isnull', False), ('sucursal__isnull', False), ('tipo_alcance', 'SUCURSAL')), _connector='OR'), name='rol_usr_alcance_valido_ck'),
        ),
        migrations.AddConstraint(
            model_name='rolusuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activo', True), ('revocado_en__isnull', True)), models.Q(('activo', False), ('revocado_en__isnull', False)), _connector='OR'), name='rol_usr_revocacion_valida_ck'),
        ),
        migrations.AddConstraint(
            model_name='rolusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'GLOBAL')), fields=('usuario', 'rol'), name='rol_usr_global_activo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rolusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'EMPRESA')), fields=('usuario', 'rol', 'empresa'), name='rol_usr_empresa_activo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rolusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'SUCURSAL')), fields=('usuario', 'rol', 'sucursal'), name='rol_usr_sucursal_activo_uniq'),
        ),
    ]
