# Generated by Django 5.2.16 on 2026-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permiso_rol_permisorol_permiso_roles_rolusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permite_alcance_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='permite_alcance_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='permite_alcance_sucursal',
            field=models.BooleanField(default=False),
        ),
    ]
