# Generated by Django 5.2.16 on 2026-09-21 17:56

from django.db import migrations


ROLES = {
    "SUPERADMINISTRADOR": {
        "nombre": "Superadministrador",
        "descripcion": "Administración total de la plataforma.",
        "permite_alcance_global": True,
        "permite_alcance_empresa": False,
        "permite_alcance_sucursal": False,
    },
    "ADMINISTRADOR_CORPORATIVO": {
        "nombre": "Administrador corporativo",
        "descripcion": "Administración del despliegue corporativo.",
        "permite_alcance_global": True,
        "permite_alcance_empresa": True,
        "permite_alcance_sucursal": False,
    },
    "SUPERVISOR_CORPORATIVO": {
        "nombre": "Supervisor corporativo",
        "descripcion": "Supervisión operativa corporativa.",
        "permite_alcance_global": False,
        "permite_alcance_empresa": True,
        "permite_alcance_sucursal": True,
    },
    "SOLICITANTE_CORPORATIVO": {
        "nombre": "Solicitante corporativo",
        "descripcion": "Creación y consulta de solicitudes corporativas.",
        "permite_alcance_global": False,
        "permite_alcance_empresa": True,
        "permite_alcance_sucursal": True,
    },
    "ADMINISTRADOR_EMPRESA_EXTERNA": {
        "nombre": "Administrador de empresa externa",
        "descripcion": "Administración de una empresa de VitaGo Network.",
        "permite_alcance_global": False,
        "permite_alcance_empresa": True,
        "permite_alcance_sucursal": False,
    },
    "SOLICITANTE_EXTERNO": {
        "nombre": "Solicitante externo",
        "descripcion": "Creación y consulta de solicitudes externas.",
        "permite_alcance_global": False,
        "permite_alcance_empresa": True,
        "permite_alcance_sucursal": True,
    },
    "OPERADOR_RED": {
        "nombre": "Operador de red",
        "descripcion": "Coordinación operativa de VitaGo Network.",
        "permite_alcance_global": True,
        "permite_alcance_empresa": False,
        "permite_alcance_sucursal": False,
    },
    "REPARTIDOR_CORPORATIVO": {
        "nombre": "Repartidor corporativo",
        "descripcion": "Ejecución de servicios del despliegue corporativo.",
        "permite_alcance_global": False,
        "permite_alcance_empresa": True,
        "permite_alcance_sucursal": False,
    },
    "REPARTIDOR_RED": {
        "nombre": "Repartidor de red",
        "descripcion": "Ejecución de servicios compartidos de VitaGo Network.",
        "permite_alcance_global": True,
        "permite_alcance_empresa": False,
        "permite_alcance_sucursal": False,
    },
}


PERMISOS = {
    "empresa.ver": ("Ver empresas", "Consultar empresas permitidas."),
    "empresa.administrar": ("Administrar empresas", "Crear y modificar empresas."),
    "sucursal.ver": ("Ver sucursales", "Consultar sucursales permitidas."),
    "sucursal.administrar": (
        "Administrar sucursales",
        "Crear y modificar sucursales.",
    ),
    "usuario.ver": ("Ver usuarios", "Consultar usuarios permitidos."),
    "usuario.administrar": (
        "Administrar usuarios",
        "Crear y modificar usuarios.",
    ),
    "rol.asignar": ("Asignar roles", "Asignar y revocar roles de usuarios."),
    "ubicacion.ver": ("Ver ubicaciones", "Consultar ubicaciones permitidas."),
    "ubicacion.crear": ("Crear ubicaciones", "Registrar ubicaciones."),
    "ubicacion.aprobar": (
        "Aprobar ubicaciones",
        "Aprobar ubicaciones para una empresa.",
    ),
    "solicitud.crear": ("Crear solicitudes", "Registrar nuevas solicitudes."),
    "solicitud.ver": ("Ver solicitudes", "Consultar solicitudes permitidas."),
    "solicitud.asignar": (
        "Asignar solicitudes",
        "Asignar solicitudes a repartidores.",
    ),
    "solicitud.reasignar": (
        "Reasignar solicitudes",
        "Cambiar el repartidor de una solicitud.",
    ),
    "solicitud.cancelar": ("Cancelar solicitudes", "Cancelar solicitudes."),
    "solicitud.actualizar_estado": (
        "Actualizar estado de solicitud",
        "Ejecutar transiciones operativas permitidas.",
    ),
    "solicitud.ver_seguimiento": (
        "Ver seguimiento de solicitud",
        "Consultar seguimiento autorizado de una solicitud activa.",
    ),
    "repartidor.ver": ("Ver repartidores", "Consultar repartidores permitidos."),
    "repartidor.administrar": (
        "Administrar repartidores",
        "Administrar perfiles operativos de repartidores.",
    ),
    "repartidor.ver_ubicacion": (
        "Ver ubicación de repartidores",
        "Consultar ubicación operativa autorizada.",
    ),
    "repartidor.actualizar_estado": (
        "Actualizar estado del repartidor",
        "Cambiar el estado operativo propio.",
    ),
    "repartidor.actualizar_capacidad": (
        "Actualizar capacidad del repartidor",
        "Cambiar la capacidad operativa propia.",
    ),
    "ruta.ver": ("Ver rutas", "Consultar rutas permitidas."),
    "ruta.administrar": ("Administrar rutas", "Crear y modificar rutas."),
    "evidencia.crear": ("Crear evidencias", "Registrar evidencias operativas."),
    "evidencia.ver": ("Ver evidencias", "Consultar evidencias permitidas."),
    "incidencia.crear": ("Crear incidencias", "Registrar incidencias operativas."),
    "incidencia.revisar": ("Revisar incidencias", "Revisar incidencias reportadas."),
    "jornada.iniciar": ("Iniciar jornada", "Iniciar la jornada propia."),
    "jornada.finalizar": ("Finalizar jornada", "Finalizar la jornada propia."),
    "jornada.ver": ("Ver jornadas", "Consultar jornadas permitidas."),
    "vehiculo.ver": ("Ver vehículos", "Consultar vehículos permitidos."),
    "vehiculo.administrar": (
        "Administrar vehículos",
        "Crear y modificar vehículos y mantenimiento.",
    ),
    "reporte.ver": ("Ver reportes", "Consultar reportes permitidos."),
    "configuracion.administrar": (
        "Administrar configuración",
        "Modificar configuración operativa.",
    ),
    "tarifa.ver": ("Ver tarifas", "Consultar tarifas y cotizaciones."),
    "tarifa.administrar": ("Administrar tarifas", "Crear y modificar tarifas."),
}


PERMISOS_SOLICITANTE = {
    "ubicacion.ver",
    "solicitud.crear",
    "solicitud.ver",
    "solicitud.ver_seguimiento",
    "evidencia.ver",
}

PERMISOS_REPARTIDOR = {
    "ubicacion.ver",
    "solicitud.ver",
    "solicitud.actualizar_estado",
    "repartidor.actualizar_estado",
    "repartidor.actualizar_capacidad",
    "ruta.ver",
    "evidencia.crear",
    "evidencia.ver",
    "incidencia.crear",
    "jornada.iniciar",
    "jornada.finalizar",
    "jornada.ver",
    "vehiculo.ver",
}

MATRIZ_ROLES = {
    "SUPERADMINISTRADOR": set(PERMISOS),
    "ADMINISTRADOR_CORPORATIVO": {
        "empresa.ver",
        "empresa.administrar",
        "sucursal.ver",
        "sucursal.administrar",
        "usuario.ver",
        "usuario.administrar",
        "rol.asignar",
        "ubicacion.ver",
        "ubicacion.crear",
        "ubicacion.aprobar",
        "solicitud.crear",
        "solicitud.ver",
        "solicitud.asignar",
        "solicitud.reasignar",
        "solicitud.cancelar",
        "solicitud.actualizar_estado",
        "solicitud.ver_seguimiento",
        "repartidor.ver",
        "repartidor.administrar",
        "repartidor.ver_ubicacion",
        "ruta.ver",
        "ruta.administrar",
        "evidencia.ver",
        "incidencia.revisar",
        "jornada.ver",
        "vehiculo.ver",
        "vehiculo.administrar",
        "reporte.ver",
        "configuracion.administrar",
    },
    "SUPERVISOR_CORPORATIVO": {
        "empresa.ver",
        "sucursal.ver",
        "usuario.ver",
        "ubicacion.ver",
        "solicitud.ver",
        "solicitud.asignar",
        "solicitud.reasignar",
        "solicitud.cancelar",
        "solicitud.ver_seguimiento",
        "repartidor.ver",
        "repartidor.administrar",
        "repartidor.ver_ubicacion",
        "ruta.ver",
        "ruta.administrar",
        "evidencia.ver",
        "incidencia.revisar",
        "jornada.ver",
        "vehiculo.ver",
        "reporte.ver",
    },
    "SOLICITANTE_CORPORATIVO": set(PERMISOS_SOLICITANTE),
    "ADMINISTRADOR_EMPRESA_EXTERNA": {
        "empresa.ver",
        "empresa.administrar",
        "sucursal.ver",
        "sucursal.administrar",
        "usuario.ver",
        "usuario.administrar",
        "rol.asignar",
        "ubicacion.ver",
        "ubicacion.crear",
        "ubicacion.aprobar",
        "solicitud.crear",
        "solicitud.ver",
        "solicitud.cancelar",
        "solicitud.ver_seguimiento",
        "evidencia.ver",
        "reporte.ver",
        "tarifa.ver",
    },
    "SOLICITANTE_EXTERNO": set(PERMISOS_SOLICITANTE) | {"tarifa.ver"},
    "OPERADOR_RED": {
        "empresa.ver",
        "sucursal.ver",
        "usuario.ver",
        "ubicacion.ver",
        "solicitud.ver",
        "solicitud.asignar",
        "solicitud.reasignar",
        "solicitud.cancelar",
        "solicitud.ver_seguimiento",
        "repartidor.ver",
        "repartidor.administrar",
        "repartidor.ver_ubicacion",
        "ruta.ver",
        "ruta.administrar",
        "evidencia.ver",
        "incidencia.revisar",
        "jornada.ver",
        "vehiculo.ver",
        "reporte.ver",
        "tarifa.ver",
    },
    "REPARTIDOR_CORPORATIVO": set(PERMISOS_REPARTIDOR),
    "REPARTIDOR_RED": set(PERMISOS_REPARTIDOR),
}


def crear_catalogo_autorizacion(aplicaciones, editor_esquema):
    Rol = aplicaciones.get_model("usuarios", "Rol")
    Permiso = aplicaciones.get_model("usuarios", "Permiso")
    PermisoRol = aplicaciones.get_model("usuarios", "PermisoRol")

    roles = {}
    for codigo, datos in ROLES.items():
        rol, _ = Rol._default_manager.update_or_create(
            codigo=codigo,
            defaults={**datos, "activo": True},
        )
        roles[codigo] = rol

    permisos = {}
    for codigo, (nombre, descripcion) in PERMISOS.items():
        permiso, _ = Permiso._default_manager.update_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "descripcion": descripcion,
                "activo": True,
            },
        )
        permisos[codigo] = permiso

    ids_permisos_catalogo = [permiso.pk for permiso in permisos.values()]
    for codigo_rol, codigos_permisos in MATRIZ_ROLES.items():
        rol = roles[codigo_rol]
        ids_asignados = []
        for codigo_permiso in codigos_permisos:
            permiso = permisos[codigo_permiso]
            ids_asignados.append(permiso.pk)
            PermisoRol._default_manager.update_or_create(
                rol_id=rol.pk,
                permiso_id=permiso.pk,
                defaults={"activo": True},
            )

        relaciones = PermisoRol._default_manager.filter(
            rol_id=rol.pk,
            permiso_id__in=ids_permisos_catalogo,
        )
        relaciones.exclude(permiso_id__in=ids_asignados).update(activo=False)


def desactivar_catalogo_autorizacion(aplicaciones, editor_esquema):
    Rol = aplicaciones.get_model("usuarios", "Rol")
    Permiso = aplicaciones.get_model("usuarios", "Permiso")
    PermisoRol = aplicaciones.get_model("usuarios", "PermisoRol")

    PermisoRol._default_manager.filter(
        rol__codigo__in=ROLES,
        permiso__codigo__in=PERMISOS,
    ).update(activo=False)
    Rol._default_manager.filter(codigo__in=ROLES).update(activo=False)

    for permiso in Permiso._default_manager.filter(codigo__in=PERMISOS):
        usado_por_otro_rol = (
            PermisoRol._default_manager.filter(
                permiso_id=permiso.pk,
                activo=True,
            )
            .exclude(rol__codigo__in=ROLES)
            .exists()
        )
        if not usado_por_otro_rol:
            Permiso._default_manager.filter(pk=permiso.pk).update(activo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alcances_permitidos_rol'),
    ]

    operations = [
        migrations.RunPython(
            crear_catalogo_autorizacion,
            desactivar_catalogo_autorizacion,
        ),
    ]
