# Generated by Django 5.2.16 on 2026-09-26 14:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaRepartidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=16)),
                ('iniciada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('latitud_inicio', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_inicio', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud_fin', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_fin', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('kilometros_operativos', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('servicios_completados', models.PositiveIntegerField(default=0)),
                ('recolecciones_completadas', models.PositiveIntegerField(default=0)),
                ('entregas_completadas', models.PositiveIntegerField(default=0)),
                ('servicios_normales', models.PositiveIntegerField(default=0)),
                ('servicios_prioritarios', models.PositiveIntegerField(default=0)),
                ('minutos_activos', models.PositiveIntegerField(default=0)),
                ('incidencias_reportadas', models.PositiveIntegerField(default=0)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'jornada de motorista',
                'verbose_name_plural': 'jornadas de motoristas',
                'db_table': 'jornadas_repartidor',
                'ordering': ('-iniciada_en', '-id'),
                'indexes': [models.Index(fields=['repartidor', '-iniciada_en'], name='jornada_repart_fecha_idx'), models.Index(fields=['estado', '-iniciada_en'], name='jornada_estado_fecha_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('repartidor',), name='jornada_repart_activa_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ACTIVA'), ('finalizada_en__isnull', True)), models.Q(('estado', 'FINALIZADA'), ('finalizada_en__isnull', False)), _connector='OR'), name='jornada_cierre_valido_ck'), models.CheckConstraint(condition=models.Q(models.Q(('latitud_inicio__isnull', True), ('longitud_inicio__isnull', True)), models.Q(('latitud_inicio__gte', -90), ('latitud_inicio__lte', 90), ('longitud_inicio__gte', -180), ('longitud_inicio__lte', 180)), _connector='OR'), name='jornada_gps_inicio_valido_ck'), models.CheckConstraint(condition=models.Q(models.Q(('latitud_fin__isnull', True), ('longitud_fin__isnull', True)), models.Q(('latitud_fin__gte', -90), ('latitud_fin__lte', 90), ('longitud_fin__gte', -180), ('longitud_fin__lte', 180)), _connector='OR'), name='jornada_gps_fin_valido_ck'), models.CheckConstraint(condition=models.Q(('kilometros_operativos__gte', 0)), name='jornada_km_no_negativos_ck')],
            },
        ),
    ]
