# Generated by Django 5.2.16 on 2026-09-26 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repartidores', '0001_initial'),
        ('solicitudes', '0003_asignacionsolicitud_solicitud_repartidor_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('FOTO_RECOLECCION', 'Fotografía de recolección'), ('FOTO_ENTREGA', 'Fotografía de entrega'), ('FOTO_INCIDENCIA', 'Fotografía de incidencia')], max_length=24)),
                ('clave_almacenamiento', models.CharField(max_length=500, unique=True)),
                ('url_archivo', models.URLField(blank=True, max_length=1000, null=True)),
                ('tipo_contenido', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capturada_en', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_solicitudes', to='repartidores.repartidor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'evidencia de solicitud',
                'verbose_name_plural': 'evidencias de solicitudes',
                'db_table': 'evidencias_solicitud',
                'ordering': ('capturada_en', 'id'),
                'indexes': [models.Index(fields=['solicitud', 'tipo', '-capturada_en'], name='evid_sol_tipo_fecha_idx'), models.Index(fields=['repartidor', '-capturada_en'], name='evid_repart_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['FOTO_RECOLECCION', 'FOTO_ENTREGA', 'FOTO_INCIDENCIA'])), name='evidencia_tipo_valido_ck'), models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='evidencia_latitud_valida_ck'), models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='evidencia_longitud_valida_ck')],
            },
        ),
    ]
